// VX9baqSEYVO9qlhXqkGoLYfYh7WpT8c4egOkL5jMg7sX3oQ6fChwu1YvVvsSfkmLWsF1JZUj9oL2gK96zDsDNwfRhKiV0GnffNXJVl7z33RpufRXq0ZOdPVx40CfnCX9ByEJsdZLGPZSTNWae7yqkVHpxwMhBArM+9uILmcyM+03v+w6nIh9k+45JsapUuj46ItFkGO+GCWjA5i+0m3F3AqLU5gn1k31ZcVFC8swPl9XY7eytT5vDM46p8sT4uY6NKd7xLMuOY9dHQeGySwHKCCrPU2hcv4Lwc9nqqT8fi/InrCgzSewJcof/8TZDt7+2NZmomFFx11GGve8g8JAYg==
/**
** Copyright (C) 2000-2014 Opera Software ASA.  All rights reserved.
**
** This file is part of the Opera web browser.
**
** This script patches sites to work better with Opera
** For more information see http://www.opera.com/docs/browserjs/
**
** If you have comments on these patches (for example if you are the webmaster
** and want to inform us about a fixed site that no longer needs patching)
** please report issues through the bug tracking system
** https://bugs.opera.com/
**
** DO NOT EDIT THIS FILE! It will not be used by Opera if edited.
**/
// Generic fixes (mostly)
(function(){
	var bjsversion = " Opera OPRMobile 15.0 core 1162.59591, March 10, 2014." +
					 " Active patches: 4 ";
	var navRestore = {}; // keep original navigator.* values
	var shouldRestore = false;

	var href = location.href;
	var pathname = location.pathname;
	var hostname = {
		value: location.hostname,
		toString: function() {
			return this.value;
		},
		valueOf: function() {
			return this.value;
		},
		indexOf: function(string) {
			return this.value.indexOf(string);
		},
		match: function(regex) {
			return this.value.match(regex);
		},
		contains: function(string) {
			return this.value.indexOf(string) > -1;
		},
		endsWith: function(suffix) {
			return this.value.indexOf(suffix, this.value.length - suffix.length) !== -1;
		}
	}

	/* We make references to the following functions to not get version that users
	have overwritten */
	var call = Function.prototype.call;
	var getElementsByTagName = Document.prototype.getElementsByTagName;
	var addEventListener = Window.prototype.addEventListener;
	var createElement = Document.prototype.createElement;
	var createTextNode = Document.prototype.createTextNode;
	var insertBefore = Node.prototype.insertBefore;
	var setAttribute = Element.prototype.setAttribute;
	var appendChild = Node.prototype.appendChild;
	var setTimeout = window.setTimeout;

	function log(str) {
		if (self != top || str.match(/^0,/)) {
			return;
		}
		console.log("Opera has modified script or content on "
								+ hostname + " (" + str + "). See browser.js for details");
	}


	// Utility functions


	// ANDMO-1210, Replace Youtube embeds with image and link on Android devices with no plugins.

	document.addEventListener("DOMContentLoaded", function (e) {
		if( ( navigator.platform == "Android" || navigator.platform.indexOf("Linux armv") == 0 ) && !navigator.plugins.length ){
			var xpath = '//object[starts-with(@data,"http://www.youtube.com/v/")] | //object//param[starts-with(@name,"src") and starts-with(@value,"http://www.youtube.com/v/")] | //embed[starts-with(@src,"http://www.youtube.com/v/")] | //object[starts-with(@data,"https://www.youtube.com/v/")] | //object//param[starts-with(@name,"src") and starts-with(@value,"https://www.youtube.com/v/")] | //embed[starts-with(@src,"https://www.youtube.com/v/")]';
			var nodes = document.evaluate(xpath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE,null);
			for ( var i = nodes.snapshotLength-1; i >= 0 ; i-- ) {	
				var id;
				var element = nodes.snapshotItem(i);
				var uri = document.createElement('a');
				uri.href = (element.src) ? element.src : (element.data) ? element.data : (element.value) ? element.value : "";
				id = (uri.pathname.match(/embed\//)) ?  uri.pathname.split(/embed\//)[1] : uri.pathname.split(/v\//)[1];		
				id = id.split(/&/)[0];
				var VidUrl = document.createElement('a');
				VidUrl.href = "vnd.youtube:" + id;
				var ThumbImage= document.createElement('img');
				ThumbImage.src = "http://img.youtube.com/vi/"+id+"/1.jpg";
				ThumbImage.width = (element.width) ? element.width : element.parentNode.width;
				ThumbImage.height = (element.height) ? element.height : element.parentNode.height;	
				VidUrl.appendChild(ThumbImage);
				element.parentNode.replaceChild(VidUrl, element);
			}
		 }
	}, false);


	if(hostname.contains('www.bing.')){
		window.addEventListener('resize',function(){
			var ev = new CustomEvent('orientationchange');
			window.dispatchEvent(ev);
		},false);
		log('PATCH-1153, Bing - fix viewport after rotation');
	} else if(hostname.indexOf('.yahoo.')>-1){
		/* Yahoo! */
		log('0, Yahoo!');
	} else if(hostname.indexOf('opera.com')>-1&& pathname.indexOf('/docs/browserjs/')==0){
		document.addEventListener('DOMContentLoaded',function(){
			if(document.getElementById('browserjs_active')){
				document.getElementById('browserjs_active').style.display='';
				document.getElementById('browserjs_active').getElementsByTagName('span')[0].appendChild(document.createTextNode(bjsversion));
				document.getElementById('browserjs_status_message').style.display='none';
			}else if(document.getElementById('browserjs_status_message')){
				document.getElementById('browserjs_status_message').firstChild.data='Browser.js is enabled! '+bjsversion;
			}
		}, false);
		log('1, Browser.js status and version reported on browser.js documentation page');
	}

})();
