// trn1nD06HfeyPirj0ZJFS8WNC7Jgg9xdAJ/wK2PEFL2AEnk9mWoQJd1KCQqTt0A5OnUiBKiPnWAz2nvOsvLALQW8cgKOvj7SO4409JFBDdLTMNmw7OFWJCqOdumcxpM2rH1MHzH5FjUj1lANwlegzgzDSNsL8jKzidBPf2Nfv6mOE86A1YsRaqCnUQLyVTAarFaeE3WJvPPzoEuz+Bg+HvQ7ZON1zUYQ3ZSBy6zW5gBlPv+wrqULjovDQx9sJdjRrEHQQ3HzMtvDBoqr+hix9dVGe6A6OK2io1+R19IBPgoK64d7cAuLnpHBS/W2/I+ctYIVC+xMsGAF21Htzo+7tA==
/**
** Copyright (C) 2000-2013 Opera Software ASA.  All rights reserved.
**
** This file is part of the Opera web browser.
**
** This script patches sites to work better with Opera
** For more information see http://www.opera.com/docs/browserjs/
**
** If you have comments on these patches (for example if you are the webmaster
** and want to inform us about a fixed site that no longer needs patching) please
** report issues through the bug tracking system
** https://bugs.opera.com/
**
** DO NOT EDIT THIS FILE! It will not be used by Opera if edited.
**/
// Generic fixes (mostly)
(function(){
	var bjsversion=' Opera OPRDesktop 15.0 core 1147.104, November 22, 2013. Active patches: 9 ';
	// variables and utility functions
	var navRestore = {}; // keep original navigator.* values
	var shouldRestore = false;
	var hostname = {
		value:location.hostname, 
		toString:function(){return this.value;},
		valueOf:function(){return this.value;}, 
		indexOf:function(str){return this.value.indexOf(str);},
		match: function(rx){ return this.value.match(rx); },
		contains:function(str){ return this.value.indexOf(str)>-1; },
		endsWith:function(str){ var pos=this.value.indexOf(str);return pos>-1 && this.value.length===pos+str.length; }
	}
	var href = location.href;
	var pathname=location.pathname;
	var call = Function.prototype.call,
	getElementsByTagName=Document.prototype.getElementsByTagName,
	addEventListener=Window.prototype.addEventListener,
	createElement=Document.prototype.createElement,
	createTextNode=Document.prototype.createTextNode,
	insertBefore=Node.prototype.insertBefore,
	setAttribute=Element.prototype.setAttribute,
	appendChild=Node.prototype.appendChild,
	setTimeout=window.setTimeout;
	function log(str){if(self==top && !str.match(/^0,/))console.log('Opera has modified script or content on '+hostname+' ('+str+'). See browser.js for details');}


	// Utility functions



	if(hostname.endsWith('my.tnt.com')){
		var _orig_clearPrintBlock;
		function handleMediaChange(mql) {
			if (mql.matches) {
				if(typeof clearPrintBlock == "function"){
					_orig_clearPrintBlock = clearPrintBlock;
					clearPrintBlock = function(){}
				}
			} else {
				if(typeof _orig_clearPrintBlock == "function"){
					setTimeout(_orig_clearPrintBlock, 500);
				}
			}
		}
		
		document.addEventListener('DOMContentLoaded', function() {
			var mpl = window.matchMedia("print");
			mpl.addListener(handleMediaChange);
		},false);
		log('PATCH-1156, my.tnt.com - fix empty printout');
	} else if(hostname.endsWith('www.stanserhorn.ch')){
		navigator.__defineGetter__('vendor',function(){return 'Google Inc.'});
		log('OTWK-21, stanserhorn.ch - fix UDM sniffing');
	} else if(hostname.indexOf('.google.')>-1){
		/* Google */
	
	
		if(hostname.contains('docs.google.')){
			document.addEventListener('DOMContentLoaded',function(){
				var elm = document.querySelector('a[href="http://whatbrowser.org"] + a + a');
				if(elm){elm.click();}
			},false);
			log('PATCH-1032, Google Docs - auto-close unsupported browser message');
		}
		if(hostname.contains('translate.google.')){
			document.addEventListener('DOMContentLoaded',
				function(){
					var obj = '<object type="application/x-shockwave-flash" data="//ssl.gstatic.com/translate/sound_player2.swf" width="18" height="18" id="tts"><param value="//ssl.gstatic.com/translate/sound_player2.swf" name="movie"><param value="sound_name_cb=_TTSSoundFile" name="flashvars"><param value="transparent" name="wmode"><param value="always" name="allowScriptAccess"></object>';
					var aud = document.getElementById('tts');
					if(aud && aud instanceof HTMLAudioElement && aud.parentNode.childNodes.length == 1){
						aud.parentNode.innerHTML = obj;
					}
				}
			,false);
			log('PATCH-1148, Google Translate: use flash instead of mp3-audio');
		}
		log('0, Google');
	} else if(hostname.indexOf('.yahoo.')>-1){
		/* Yahoo! */
		log('0, Yahoo!');
	} else if(hostname.indexOf('opera.com')>-1&& pathname.indexOf('/docs/browserjs/')==0){
		document.addEventListener('DOMContentLoaded',function(){
			if(document.getElementById('browserjs_active')){
				document.getElementById('browserjs_active').style.display='';
				document.getElementById('browserjs_active').getElementsByTagName('span')[0].appendChild(document.createTextNode(bjsversion));
				document.getElementById('browserjs_status_message').style.display='none';
			}else if(document.getElementById('browserjs_status_message')){
				document.getElementById('browserjs_status_message').firstChild.data='Browser.js is enabled! '+bjsversion;
			}
		}, false);
		log('1, Browser.js status and version reported on browser.js documentation page');
	} else if(href==='https://bugs.opera.com/wizarddesktop/'){
		document.addEventListener('DOMContentLoaded', function(){
			var frm;
			if(document.getElementById('bug') instanceof HTMLFormElement){
				frm=document.getElementById('bug');
				if(frm.auto)frm.auto.value+='\n\nBrowser JavaScript: \n'+bjsversion;
			}
		}, false);
		log('PATCH-221, Include browser.js timestamp in bug reports');
	} else if(pathname.indexOf('/AnalyticalReporting/')==0){
		if(pathname.indexOf('AnalyticalReporting/WebiModify.do')>-1 || pathname.indexOf('AnalyticalReporting/WebiCreate.do')>-1){
			Object.defineProperty(window, 'embed_size_attr', {
				get:function(){return this._foobar},
				set:function(arg){
					if(arg=='style="width: 100%; height: 100%;')this._foobar='style="width: 100%; height: 100%;"';
					else this._foobar = arg;
				}
			});	
		}
		log('PATCH-555, Analytix: add missing end quote');
	}

})();